###############################################
################# SPOILER ALERT ###############
###############################################



############## DEBUG ##########################
debug: false
log.recipes.enable: false

spoileralert-set-expiration-on-inventory-click: true

spoileralert-base-debuf-duration-in-seconds: 30

spoileralert-blinding-enabled: true
spoileralert-confusion-enabled: true

spoileralert-harm-enabled: true
spoileralert-age-before-harm-as-proportion-of-shelf-life: 3

spoileralert-decrease-food-level-enabled: true
spoileralert-decrease-saturation-enabled: true

spoileralert-recipe-shelf-life: 
  - Candy Apple=21
  - Salted Beef=21
  
spoileralert-shelf-life: 
  - APPLE=7
  - BAKED_POTATO=5
  - BEETROOT=7
  - BEETROOT_SOUP=7
  - BROWN_MUSHROOM=10
  - CAKE=14
  - CARROT=7
  - CARROT_ITEM=7
  - CHORUS_FRUIT=5
  - COOKED_BEEF=7
  - COOKED_CHICKEN=7
  - COOKED_FISH=7
  - COOKED_MUTTON=7
  - COOKED_RABBIT=7
  - COOKIE=14
  - CROPS=21
  - EGG=10
  - MILK_BUCKET=14
  - MELON=7
  - MELON_BLOCK=7
  - MUSHROOM_SOUP=5
  - MUTTON=2
  - PORK=2
  - POTATO=21
  - POTATO_ITEM=21
  - PUMPKIN=7
  - PUMPKIN_PIE=7
  - RABBIT_STEW=7
  - RAW_BEEF=2
  - RAW_CHICKEN=2
  - RAW_FISH=2
  - RED_MUSHROOM=10
  - SPECKLED_MELON=7
  - WHEAT=21




############## RECIPES ############
recipes:
  - candy-apple
  - coarse-salt
  - salted-beef


###############################################
#################### RECIPES ##################
###############################################


################## BEGIN Candy Apple ############
recipe.candy-apple.name: Candy Apple
recipe.candy-apple.rows: 
  - RSR
  - SAS
  - RTR
recipe.candy-apple.mats: 
  - S=SUGAR
  - A=APPLE
  - T=STICK
  - R-AIR
recipe.candy-apple.output: APPLE


################## BEGIN Coarse Salt #################
recipe.coarse-salt.name: Coarse Salt
recipe.coarse-salt.rows: 
  - AWA
  - ACA
  - ASA
recipe.coarse-salt.mats: 
  - S=SAND
  - C=COAL
  - W=WATER_BUCKET
recipe.coarse-salt.output: SUGAR
recipe.coarse-salt.amount: 4


################## BEGIN Salted Beef #################
recipe.salted-beef.name: Salted Beef
recipe.salted-beef.rows: 
  - ASA
  - SBS
  - ASA
recipe.salted-beef.mats: 
  - A=AIR
  - B=COOKED_BEEF
  - S=SUGAR
recipe.salted-beef.output: COOKED_BEEF
recipe.salted-beef.item.starts.with: 
  - 1=Coarse Salt
  - 3=Coarse Salt
  - 5=Coarse Salt
  - 7=Coarse Salt















  
  
  
  
  
  
