###############################################
################# SPOILER ALERT ###############
###############################################



############## DEBUG ##########################
locale: en
debug: false
log.recipes.enable: false

spoileralert-use-real-dates: true

spoileralert-base-debuf-duration-in-seconds: 30

spoileralert-blinding-enabled: true
spoileralert-confusion-enabled: true

spoileralert-harm-enabled: true
spoileralert-age-before-harm-as-proportion-of-shelf-life: 3

spoileralert-decrease-food-level-enabled: true
spoileralert-decrease-saturation-enabled: true

spoileralert-date-format.en_us: M/d/yyyy
spoileralert-date-format.zh_cn: yyyy-MM-dd
spoileralert-date-format.de: yyyy-MM-dd

spoileralert-recipe-shelf-life: 
  - candy-apple=21
  - salted-beef=21
  - salted-pork=21
  - salted-fish=21
  - salted-chicken=21
  - salted-mutton=21
  
spoileralert-shelf-life: 
  - APPLE=7
  - BAKED_POTATO=5
  - BEETROOT=7
  - BEETROOT_SOUP=7
  - BREAD=14
  - BROWN_MUSHROOM=10
  - CAKE=14
  - CARROT=7
  - CARROT_ITEM=7
  - CHORUS_FRUIT=5
  - COOKED_BEEF=7
  - COOKED_CHICKEN=7
  - COOKED_FISH=7
  - COOKED_MUTTON=7
  - COOKED_RABBIT=7
  - COOKIE=14
  - CROPS=21
  - EGG=10
  - GRILLED_PORK=7
  - MILK_BUCKET=14
  - MELON=7
  - MELON_BLOCK=7
  - MUSHROOM_SOUP=5
  - MUTTON=2
  - PORK=2
  - POTATO=21
  - POTATO_ITEM=21
  - PUMPKIN=7
  - PUMPKIN_PIE=7
  - RABBIT_STEW=7
  - RAW_BEEF=2
  - RAW_CHICKEN=2
  - RAW_FISH=2
  - RED_MUSHROOM=10
  - SPECKLED_MELON=7
  - WHEAT=21




############## RECIPES ############
recipes:
  - candy-apple
  - coarse-salt
  - salted-beef
  - salted-pork
  - salted-fish
  - salted-chicken
  - salted-mutton


###############################################
#################### RECIPES ##################
###############################################

recipes-settings.continuous-translation: true

################## BEGIN Candy Apple ############
recipe.candy-apple.name: Candy Apple
recipe.candy-apple.de.name: Kandierter Apfel
recipe.candy-apple.fr.name: Pomme confite
recipe.candy-apple.es.name: Manzana de caramelo
recipe.candy-apple.vi.name: táo kẹo
recipe.candy-apple.locales:
  - de
  - fr
  - es
  - vi
recipe.candy-apple.rows: 
  - RSR
  - SAS
  - RTR
recipe.candy-apple.mats: 
  - S=SUGAR
  - A=APPLE
  - T=STICK
  - R-AIR
recipe.candy-apple.output: APPLE


################## BEGIN Coarse Salt #################
recipe.coarse-salt.name: Coarse Salt
recipe.coarse-salt.de.name: grobes Salz
recipe.coarse-salt.fr.name: gros sel
recipe.coarse-salt.es.name: sal gruesa
recipe.coarse-salt.vi.name: Muối thô
recipe.coarse-salt.locales: 
  - de
  - fr
  - es
  - vi
recipe.coarse-salt.rows: 
  - AWA
  - ACA
  - ASA
recipe.coarse-salt.mats: 
  - S=SAND
  - C=COAL
  - W=WATER_BUCKET
recipe.coarse-salt.output: SUGAR
recipe.coarse-salt.amount: 4


################## BEGIN Salted Beef #################
recipe.salted-beef.name: Salted Beef
recipe.salted-beef.de.name: Gepökeltes Rindfleisch
recipe.salted-beef.fr.name: boeuf salé
recipe.salted-beef.es.name: Carne de vaca salada
recipe.salted-beef.vi.name: thịt bò ướp muối
recipe.salted-beef.locales: 
  - de
  - fr
  - es
  - vi
recipe.salted-beef.rows: 
  - ASA
  - SBS
  - ASA
recipe.salted-beef.mats: 
  - A=AIR
  - B=COOKED_BEEF
  - S=SUGAR
recipe.salted-beef.output: COOKED_BEEF
recipe.salted-beef.item-has-nbt-key: 
  - 1=coarse-salt
  - 3=coarse-salt
  - 5=coarse-salt
  - 7=coarse-salt
  
  
################## BEGIN Salted Pork #################
recipe.salted-pork.name: Salted Pork
recipe.salted-pork.de.name: Gepökeltes Schweinefleisch
recipe.salted-pork.fr.name: porc salé
recipe.salted-pork.es.name: Carne de cerdo salada
recipe.salted-pork.vi.name: Thịt lợn muối
recipe.salted-pork.locales: 
  - de
  - fr
  - es
  - vi
recipe.salted-pork.rows: 
  - ASA
  - SPS
  - ASA
recipe.salted-pork.mats: 
  - A=AIR
  - P=GRILLED_PORK
  - S=SUGAR
recipe.salted-pork.output: GRILLED_PORK
recipe.salted-pork.item-has-nbt-key: 
  - 1=coarse-salt
  - 3=coarse-salt
  - 5=coarse-salt
  - 7=coarse-salt
  
  
################## BEGIN Salted Fish #################
recipe.salted-fish.name: Salted Fish
recipe.salted-fish.de.name: Gepökelter Fisch
recipe.salted-fish.fr.name: Le poisson salé
recipe.salted-fish.es.name: pescado salado
recipe.salted-fish.vi.name: Cá ướp muối
recipe.salted-fish.locales: 
  - de
  - fr
  - es
  - vi
recipe.salted-fish.rows: 
  - ASA
  - SFS
  - ASA
recipe.salted-fish.mats: 
  - A=AIR
  - F=COOKED_FISH
  - S=SUGAR
recipe.salted-fish.output: COOKED_FISH
recipe.salted-fish.item-has-nbt-key: 
  - 1=coarse-salt
  - 3=coarse-salt
  - 5=coarse-salt
  - 7=coarse-salt


################## BEGIN Salted Chicken #################
recipe.salted-chicken.name: Salted Chicken
recipe.salted-chicken.de.name: Gepökeltes Huhn
recipe.salted-chicken.fr.name: poulet salé
recipe.salted-chicken.es.name: pollo salado
recipe.salted-chicken.vi.name: gà muối
recipe.salted-chicken.locales: 
  - de
  - fr
  - es
  - vi
recipe.salted-chicken.rows: 
  - ASA
  - SCS
  - ASA
recipe.salted-chicken.mats: 
  - A=AIR
  - C=COOKED_CHICKEN
  - S=SUGAR
recipe.salted-chicken.output: COOKED_CHICKEN
recipe.salted-chicken.item-has-nbt-key: 
  - 1=coarse-salt
  - 3=coarse-salt
  - 5=coarse-salt
  - 7=coarse-salt


################## BEGIN Salted Mutton #################
recipe.salted-mutton.name: Salted Mutton
recipe.salted-mutton.de.name: Gepökelter Hammel
recipe.salted-mutton.fr.name: salé Mouton
recipe.salted-mutton.es.name: salado cordero
recipe.salted-mutton.vi.name: muối Thịt cừu
recipe.salted-mutton.locales: 
  - de
  - fr
  - es
  - vi
recipe.salted-mutton.rows: 
  - ASA
  - SMS
  - ASA
recipe.salted-mutton.mats: 
  - A=AIR
  - M=COOKED_MUTTON
  - S=SUGAR
recipe.salted-mutton.output: COOKED_MUTTON
recipe.salted-mutton.item-has-nbt-key: 
  - 1=coarse-salt
  - 3=coarse-salt
  - 5=coarse-salt
  - 7=coarse-salt



messages.spoileralert-perishable.fallback: Perishable
messages.spoileralert-expiration-date.fallback: Expiration Date
messages.spoileralert-cake-has-no-expiration-date.fallback: This cake has no expiration date.
messages.spoileralert-cake-not-expired.fallback: This cake is not expired.
messages.spoileralert-hit-cakes-first.fallback: Next time hit the cake first to find out if it is still good to eat.
messages.spoileralert-expired-message.fallback: EXPIRED {0} days- ☣ {1}
messages.spoileralert-date.fallback: Date

messages.spoileralert-perishable.de: Leicht Verderblich
messages.spoileralert-expiration-date.de: Verfallsdatum
messages.spoileralert-cake-has-no-expiration-date.de: Dieser Kuchen hat kein Verfallsdatum.
messages.spoileralert-cake-not-expired.de: Dieser Kuchen ist nicht verdorben.
messages.spoileralert-hit-cakes-first.de: Schlage, nächstes Mal erst den Kuchen, um herauszufinden, ober noch genießbar ist, oder nicht.
messages.spoileralert-expired-message.de: Verdorben seit {0} Tage(n)- Gefahrenstufe {1}
messages.spoileralert-date.de: Datum






  
  
  
  
  
  
