name: SpoilerAlert
version: 1.1.3
main:  com.blocktyper.spoileralert.SpoilerAlertPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Does this smell weird to you?
commands:
  spoil-date: 
    description: Displays date
  spoil-hunger: 
    description: OP only. Cuts hunger level in half.
  spoil-day: 
    description: OP only. Ads or substracts days.
